version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: hawkop
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.Commit}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: azconger
    name: hawkop
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## HawkOp CLI v{{.Version}}
    
    StackHawk command-line companion tool for managing organizations, users, teams, applications, and security scans.
  footer: |
    **Full Changelog**: https://github.com/azconger/hawkop/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: hawkop
    homepage: https://github.com/azconger/hawkop
    description: "StackHawk CLI companion tool"
    license: MIT
    repository:
      owner: azconger
      name: homebrew-tap
    directory: Formula
    test: |
      system "#{bin}/hawkop version"